<?php
/**
 * Created by PhpStorm.
 * User: A7ttim
 * Date: 04.10.2017
 * Time: 15:34
 */

namespace Classes\Preferences;

abstract class Decorator extends Preference
{
    private $preference;
    public function __construct(Preference $preference) {
        $this->preference = $preference;
    }

    public function getDescription()
    {
        $this->preference->getDescription();
        parent::getDescription(); // TODO: Change the autogenerated stub
    }

    public function getType()
    {
        return $this->preference->getType().$this->symbol;
        //parent::getType(); // TODO: Change the autogenerated stub
    }
}